### ISSUE TITLE
Please add me as member

### ISSUE THREAD

**Issue by Sgburman** [Myfanwy/MultilevelModelingGroup#1]

**Comment by Sgburman** [comment]
I'm going to fork and add some files to the fork, feel free to pull to master.

Scott

**Comment by Sgburman** [comment]
Also, I noticed that this repo is public, if we're going to share lit, it should probably be private, which means moving it under UCD. I'm going to move my fork under UCD, private. If you want to pull to my branch, that would make the whole repo private.

**Comment by Myfanwy** [comment]
Sorry Scott, I'm not familiar with UCD's github account - is it [this one](https://github.com/ucdavis)?  If so, what's the process for sending a pull request?

**Comment by Sgburman** [comment]
Github works a bit differently than straight git. If you've added me to the
group, I may be able to request a transfer to under ucdavis, I'll take a
look in a bit. Sorry, I've got a lot of books and papers that I'd love to
share, but I'm hesitant to do so publicly.

I'll look tonight or tomorrow.

Thanks
Scott

**Comment by Myfanwy** [comment]
Sounds good!  Thanks

**Comment by Sgburman** [comment]
If you go into settings, you can transfer ownership to ucdavis. This would move the group into ucdavis, they have a paid account, allowing you to make it private.

**Comment by Myfanwy** [comment]
Looks like it's been forked by ucdavis: https://github.com/ucdavis/MultilevelModelingGroup/

When I tried to transfer ownership it said it already exists and I don't have admin rights.  I'll send a pull request (the fork is an old version)...I'll talk to Adam re: getting admin rights.
